name: cache
on:
  workflow_dispatch:

jobs:
  cache:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod          
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
